on:
  push:
    branches:
      - main
name: changelog
jobs:
  get_changelogs:
    name: Get Added Changelog
    runs-on: ubuntu-latest
    outputs:
      added: ${{ steps.diff_changelogs.outputs.added }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: diff_changelogs
        if: ${{ steps.files.outputs.added }}
        run: |
          ADDED=$(echo ${{ steps.files.outputs.added }})
          FILTERED=$(echo $ADDED | tr ' ' '\n' | grep -E '^(changelog)/(\w+\.json)$') # only catch changelog/*.json files
          echo "Detected changelog update: $FILTERED"
          echo "added=$FILTERED" >> $GITHUB_OUTPUT
  notify:
    needs: get_changelogs
    if: ${{ needs.get_changelogs.outputs.added}}
    name: Send ChangeLog Notifications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: setup
        run: |
          sudo apt-get install jq
          pip install pathlib
          pip install jinja-cli
      - name: Send ChangeLog Notifications
        env:
          SECURITY: ${{ secrets.TEAMS_WH_SECURITY }}
          SUPPORT: ${{ secrets.TEAMS_WH_SUPPORT }}
        run: |
          TEMPLATE_PATH="changelog/.template/default.j2"
          HEADERS='Content-type: application/json'
          FILTERED=${{ needs.get_changelogs.outputs.added }}
          echo "Detected changelog update: $FILTERED"

          for FILE in $FILTERED; do
            echo "Processing changelog: $FILE"
            CHANNELS=$(jq -r '.notify[]' $FILE)
            echo "Found channels: $CHANNELS"

            for CHANNEL in $CHANNELS; do
              echo "Sending notification to $CHANNEL"
              URL=$(eval "echo \$$CHANNEL")
              echo "Webhook URL: $URL"
              jinja -u debug -d "$FILE" "$TEMPLATE_PATH" | curl -X POST -H "$HEADERS" --data @- "$URL"
            done
          done